### ISSUE TITLE
package appgotapo: cannot find package "appgotapo" 

### ISSUE THREAD

**Issue by ruirigel** [KusoKaihatsuSha/appgotapo#1]
I don't think it's a coding problem, maybe the problem is me, being the first time trying to run go.
When i try to execute your script it shows this info in the terminal:

```
go run appgotapo -host address:553 -u username -p password -do "night_on"
package appgotapo: cannot find package "appgotapo" in any of:
        /usr/lib/go-1.13/src/appgotapo (from $GOROOT)
        /home/x/go/src/appgotapo (from $GOPATH)
```
I am trying to connect to a tapo externally by your code.
could you help me?

**Comment by KusoKaihatsuSha** [comment]
Try:
`go run github.com/KusoKaihatsuSha/appgotapo@v1 -host address:553 -u username -p password -do "night_on"`
