### ISSUE TITLE
Noob needs help

### ISSUE THREAD

**Issue by PhotonPAPA** [KusoKaihatsuSha/appgotapo#2]
I want to use your app to switch ON/OFF the night vision on my Tapo C310 camera. I have installed Go into C:\Program Files and made a batch file called Tapo.bat in my Documents folder that contains the following lines:

go run github.com/KusoKaihatsuSha/appgotapo@v1 -host address: 192.168.1.66 -u Conservatory -p ******** -do "night_on"
timeout /t 5 /nobreak >nul

The batch file appears to run ok, waits 5 sec then closes. However, on the Tapo iPhone app, the night vision mode remains on Daylight mode.

Can you please point me to where I might be doing something wrong.

Thank you.

EDIT:
Got it working with:
go run github.com/KusoKaihatsuSha/appgotapo@v1 -host=192.168.1.66 -u admin -p ******** -do "night_on"

Is there an appgotapo.exe that can be used if offline? I would like to be able to run standalone, ie:

appgotapo.exe -host=192.168.1.66 -u admin -p ******** -do "night_on"

Is this possible?

EDIT2:
Found appgotapo_windows_amd64.exe. Now works perfectly.

Many thanks for this.

**Comment by KusoKaihatsuSha** [comment]
Hello.
You can get static build manually if already installed "Go compiler"
```shell
go install github.com/KusoKaihatsuSha/appgotapo@latest
```
And you will find static build file into `%GOPATH%\bin`
