### ISSUE TITLE
Latest camera firmware 

### ISSUE THREAD

**Issue by PhotonPAPA** [KusoKaihatsuSha/appgotapo#3]
Appgotapo is not able to log in to the camera since the camera firmware was updated to the latest firmware in Dec 2023. Are you able to supply a fix for this?

**Comment by KusoKaihatsuSha** [comment]
problem on 1.3.11 ?

**Comment by PhotonPAPA** [comment]
Yes.

**Comment by KusoKaihatsuSha** [comment]
On new firmware old insecure type of auth is disabled. On `appgotapo` `v1.0.5` added digit auth.

**Comment by PhotonPAPA** [comment]
Now works. Thank you so much.
