### ISSUE TITLE
Problem trying to compile

### ISSUE THREAD

**Issue by hellishvictor** [KusoKaihatsuSha/appgotapo#7]
Hi, here when compile [source from v1.0.5](https://github.com/KusoKaihatsuSha/appgotapo/archive/refs/tags/v1.0.5.zip) I get the following:

`main.go:13:2: missing go.sum entry for module providing package github.com/KusoKaihatsuSha/gotapo (imported by github.com/KusoKaihatsuSha/appgotapo); to add:
        go get github.com/KusoKaihatsuSha/appgotapo`

I'm on Win 7 x64 SP1 using Go v1.20.14.
Cheers.

**Comment by KusoKaihatsuSha** [comment]
Hello.

To fix this, you can use the command
```
go mod tidy
```

And then try to build.

**Comment by hellishvictor** [comment]
It worked like a charm, thank you very much!
